client.showSidebarNavigation = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1e3a8a"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
showSidebarNavigation = false
toolbarMode = "minimal"

[ui]
hideTopBar = true
